### ISSUE TITLE
Issue related to ens160 crate

### ISSUE THREAD

**Issue by teamplayer3** [marvinrobot42/ens160-aq#1]
Hey, I red your Note getting an issue using the ens160 on the esp32c3. Maybe you can file an issue in the ens160 crate repo to discover the Problem?

Maybe you discovered it already from your learnings writing your own Version?

**Comment by marvinrobot42** [comment]
I think the problem I had using your ENS160 driver was that it requires the
newest embedded-hal crate which caused a compatibility issue with
esp-idf-hal.  But I see that Espressif now have newer 1.1.1 version
available.

**Comment by marvinrobot42** [comment]
In the next ens160-aq crate version I will remove the comment about my
ens160 crate problem on ESP32-C3.
