### ISSUE TITLE
Examples for STM32?

### ISSUE THREAD

**Issue by paologaleotti** [marvinrobot42/ens160-aq#2]
I'm struggling a lot on making it work, basically i cannot satisfy the i2c and delay traits, i am using stm32f103 HAL and system timers.

is it possible to add examples for stm32??

**Comment by marvinrobot42** [comment]
The STM32 series microcontrollers are more work when using Rust compared to
other microcontrollers.  I think what you need to do is use the proper
stm32xxx-hal crate for your board.  For example the stmf30x_hal or
stm32f4xx_hal...check your board specs.  An example for stm32f30x_hal looks
like:

use cortex_m_rt::entry;
use stm32f30x_hal as hal;
use hal::delay::Delay;
use hal::prelude::*;
use hal::stm32f30x;
use panic_halt;

#[entry]
fn main() -> ! {
  // some boiler plate STM32 setup code  .. hopefully you have examples of
this
  let device_p = stm32f30x::Peripheral::take().unwrap();
  let core_periphs = cortex_m::Peripheral::take().unwrap();
  let mut reset_clock_control = device_p.RCC.constraint();
  let mut clocks = reset_clock_control.cfgr.freeze(&mut flash.acr);

  let mut my_delay = Delay::new(core_periphs.SYST, clocks);

  // setup i2c_dev of course

  let mut ens160 = Ens160::new(i2c_dev, my_delay);


  If I can find some time I will dig up my stm32f?xx board and see if I can
get it working.

**Comment by marvinrobot42** [comment]
And the i2c example code fragment:

use stm32f30x_hal::{
    i2c::{BlockingI2c, DutyCycle, Mode},
    prelude::*,
    stm32,
};

    let dp = stm32::Peripherals::take().unwrap();

    let mut flash = dp.FLASH.constrain();
    let rcc = dp.RCC.constrain();

    let clocks = rcc.cfgr.freeze(&mut flash.acr);

    let mut afio = dp.AFIO.constrain();

    let mut gpiob = dp.GPIOB.split();

    let scl = gpiob.pb8.into_alternate_open_drain(&mut gpiob.crh);
    let sda = gpiob.pb9.into_alternate_open_drain(&mut gpiob.crh);

    let i2c_dev = BlockingI2c::i2c1(
        dp.I2C1,
        (scl, sda),
        &mut afio.mapr,
        Mode::Fast {
            frequency: 400_000.Hz(),
            duty_cycle: DutyCycle::Ratio2to1,
        },
        clocks,
        1000,
        10,
        1000,
        1000,
    );

**Comment by marvinrobot42** [comment]
Here some ST STM32 Discovery board example that includes both i2c and delay
creation:

use cortex_m::{asm::bkpt, iprint, iprintln};
use cortex_m_rt::entry;
use stm32f3_discovery::stm32f3xx_hal::{delay::Delay, prelude, stm32::i2c1};

use cortex_m::peripheral::ITM;
use stm32f3_discovery::{
    stm32f3xx_hal::{
        i2c::I2c,
        prelude::*,
        stm32::{self, I2C1},
    },
};

pub fn init() -> (&'static i2c1::RegisterBlock, Delay, ITM) {
   // use the code below in your main method, not in an init() fn like in
this example
    let cp = cortex_m::Peripherals::take().unwrap();
    let dp = stm32::Peripherals::take().unwrap();

    let mut flash = dp.FLASH.constrain();
    let mut rcc = dp.RCC.constrain();

    let clocks = rcc.cfgr.freeze(&mut flash.acr);

    let mut gpiob = dp.GPIOB.split(&mut rcc.ahb);
    let scl = gpiob.pb6.into_af4(&mut gpiob.moder, &mut gpiob.afrl);
    let sda = gpiob.pb7.into_af4(&mut gpiob.moder, &mut gpiob.afrl);

    let i2c_dev = I2c::new(dp.I2C1, (scl, sda), 400.khz(), clocks, &mut
rcc.apb1);


    let my_delay = Delay::new(cp.SYST, clocks);

   // then pass the i2c_dev and my_delay to the Ens160::new method.
}

**Comment by marvinrobot42** [comment]
I just realised that the STM32 specific embedded-hal crates
like stm32f3xx_hal are only embedded-hal 0.2 version compatible.  They have
not updated their hardware specific hals to embedded-hal 1.0

You would see this embedded-hal 0.2 -> 1.0 version issue in the trait
bounds errors for i2c and the delay parameters when building.  If that is
the case try downgrading your dependency in your Cargo.toml to ens160-aq =
"=0.1.4" .  That is the last embedded-hal 0.2 dependency of ens160-aq crate.

I will need to dust off my STM32 discovery board and try it out (I think
that is why I stopped using the STM32 board).

**Comment by marvinrobot42** [comment]
You can also try using the embedded-hal-compat crate to .forward() and wrap
your stm32f1xx-hal i2c bus and delay 0.2 instances to be compatible with
the recent ens160-aq versions or any other embedded-hal 1.x crate for that
matter.  I have not tried doing that but according to the documentation it
looks promising.

I shall close this issue soon.
